### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by erata** [Sommerregen/grav-plugin-themer#1]
hi, i read the document but i can not understand how to use it yet. 
you say in document: copy themer.yaml file and change it. so if i have three page: home, blog, gallery and if i want to use theme1 for home, theme2 for blog and theme3 for gallery page how can i do it?
is it possible with themer plugin.

**Comment by Sommerregen** [comment]
Hi @erata ,

sorry for not responding you in time. Concerning your question: you can set up different themes for your home, blog, and gallery pages. This is done however not in the `themer.yaml` as it suggests, but in the repsective pages and/or collections. 

For your homepage (root) you can set your base theme in the [`system.yaml`](https://github.com/getgrav/grav/blob/develop/user/config/system.yaml#L7).

For blog pages, you edit `user/pages/blog/blog.md` and add

``` yaml
theme: antimatter
```

in the frontmatter (the block enclosed with `---`) if you want to use the Antimatter theme for blog pages. For you gallery pages you open `user/pages/gallery/gallery.md` and add 

``` yaml
theme: your-gallery-theme 
```

**Comment by erata** [comment]
Thansk,
