### ISSUE TITLE
TraceableTwigEnvironment not found

### ISSUE THREAD

**Issue by mplx** [Sommerregen/grav-plugin-themer#2]
The plugin doesn't working anymore when debugging is enabled:
`Class 'Grav\Common\Twig\TraceableTwigEnvironment' not found` 

TraceableTwigEnvironment has been removed in grav 0.9.43 (commit getgrav/grav@66d5eab041a33143f49ced4781b6096e000bc2be 14 Sep 2015), however themer is still using it (themer.php line 96):

``` php
        // Update TwigCollector for DebugBar
        if ($enabled && $debug) {
          $twig->twig = new TraceableTwigEnvironment($twig->twig)
```

**Comment by Sommerregen** [comment]
Hi @mplx ,

thanks. Aou are right. Instead of removing the respective lines, I guess for backward-compatibility, I have to implement a check.

**UPDATE:** [Release v1.0.3](https://github.com/Sommerregen/grav-plugin-themer/tree/v1.0.3) fix it.
